### ISSUE TITLE
Дальнейшее развитие библиотеки?

### ISSUE THREAD

**Issue by LordVampir1983** [AlexanderBagel/FWZip#3]
Здравствуйте

Правильно ли я понимаю, что вы прекратили дальнейшую разработку данной библиотеки?

С уважением, Сергей

**Comment by AlexanderBagel** [comment]
Re: [AlexanderBagel/FWZip] Дальнейшее развитие библиотеки? (#3)


Hello lordvampir,

Приветстую, да в принципе нет, но до не пока руки не доходят

Tuesday, January 9, 2018, 8:29:26 PM, you wrote:





Здравствуйте
Правильно ли я понимаю, что вы прекратили дальнейшую разработку данной библиотеки?
С уважением, Сергей
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.





-- 
Best regards,
 Александр                            mailto:rouse79@yandex.ru

**Comment by LordVampir1983** [comment]
Хорошо, я это понимаю ::-):
